<?php

include_once('ca_testimonials.features.inc');

/**
 * Implementation of hook_perm().
 */
function ca_testimonials_perm() {
  return array('ca_testimonials change templates'); 
}

/**
 * Implementation of hook_menu().
 */
function ca_testimonials_menu() {
  $items['admin/settings/ca_testimonials'] = array(
    'title' => 'CA Testimonials: Admin',
    'description' => 'Change the look and feel of the ca_testimonials module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_testimonials_admin_settings_form'),
    'access arguments' => array('ca_testimonials change templates'),
    'file' => 'ca_testimonials.admin.inc',
    'file path' => drupal_get_path('module', 'ca_testimonials') . '/includes',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function ca_testimonials_action_info() {
  return array(
    'ca_testimonials_add_ca_testimonials_admin_action' => array(
      'type' => 'user',
      'description' => t('Add testimonials administrator role'),
    ),
    'ca_testimonials_remove_ca_testimonials_admin_action' => array(
      'type' => 'user',
      'description' => t('Remove testimonials administrator role'),
    ),
  );
}

function ca_testimonials_add_ca_testimonials_admin_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'testimonials administrator') {
      $add_roles[$key] = $role;
    }
  }
  $roles += $add_roles;
  user_save($user, array('roles' => $roles));
}

function ca_testimonials_add_ca_testimonials_admin_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Promote to Testimonials Administrator',
  );
  return $form;
}

function ca_testimonials_add_ca_testimonials_admin_action_submit(&$form, &$form_state) {
  
}

function ca_testimonials_remove_ca_testimonials_admin_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'testimonials administrator') {
      $remove_roles[$key] = $role;
    }
  }
  $roles = array_diff($roles, $remove_roles);
  user_save($user, array('roles' => $roles));
}

function ca_testimonials_remove_ca_testimonials_admin_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Demote from Testimonials Administrator',
  );
  return $form;
}

function ca_testimonials_remove_ca_testimonials_admin_action_submit(&$form, &$form_state) {
  
}

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function ca_testimonials_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;;
  }
}

/**
 * Implementation of hook_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask).
 */
function ca_testimonials_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask){
  if ($subtask['name'] == 'ca_testimonials' || $subtask['name'] == 'home' || $task['name'] == 'node_view') {
    drupal_add_css(drupal_get_path('module', 'ca_testimonials') . "/css/ca_testimonials.css", 'module', 'all', FALSE);
  }
}

/**
 * Implementation of hook_views_pre_render().
 */
function ca_testimonials_views_pre_render(&$view) {
  if ($view->name == 'testimonials') {
    drupal_add_css(drupal_get_path('module', 'ca_testimonials') . "/css/ca_testimonials.css", 'module', 'all', FALSE);
  }
}

