<?php

/**
 * Implementation of hook_install().
 */
function ca_testimonials_install() {
  variable_set('ca_testimonials_list_template', 'ca_testimonials_list_template_one');
  variable_set('ca_testimonials_node_template', 'ca_testimonials_node_template_one');
}

/**
 * Implementation of hook_uninstall().
 */
function ca_testimonials_uninstall() {
  variable_del('ca_testimonials_list_template');
  variable_del('ca_testimonials_node_template');
}
